"""Add 'is_admin' column to customers

Revision ID: d640f4b6a50a
Revises: e1bd9561ff98
Create Date: 2025-03-26 20:37:52.127464

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d640f4b6a50a"
down_revision: str | None = "e1bd9561ff98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "is_admin")
    # ### end Alembic commands ###
