"""Create index on username

Revision ID: e1bd9561ff98
Revises: 21ba247eed9b
Create Date: 2025-03-25 20:46:09.462415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bd9561ff98'
down_revision: Union[str, None] = '21ba247eed9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_username_key', 'customers', type_='unique')
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.create_unique_constraint('customers_username_key', 'customers', ['username'])
    # ### end Alembic commands ###
