"""Make some fields unique in customers table

Revision ID: ee77a362f2d3
Revises: 355e9fd9e3f2
Create Date: 2025-03-22 20:21:02.335312

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee77a362f2d3"
down_revision: str | None = "355e9fd9e3f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "customers", ["email"])
    op.create_unique_constraint(None, "customers", ["id"])
    op.create_unique_constraint(None, "customers", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "customers", type_="unique")  # type: ignore
    op.drop_constraint(None, "customers", type_="unique")  # type: ignore
    op.drop_constraint(None, "customers", type_="unique")  # type: ignore
    # ### end Alembic commands ###
